#if defined(VIEW_480x222)
#define MUI_SCROLLMENU_PLUGIN
#define MUI_DASHBOARD_PLUGIN
#define MUI_NODES_PLUGIN
#define MUI_GROUPS_PLUGIN
#define MUI_MESSAGES_PLUGIN
#define MUI_CLOCK_PLUGIN
#define MUI_MAP_PLUGIN
#define MUI_SETTINGS_PLUGIN
#endif

#if defined(VIEW_320x170)
#define MUI_SCROLLMENU_PLUGIN
#define MUI_DASHBOARD_PLUGIN
#define MUI_NODES_PLUGIN
#define MUI_GROUPS_PLUGIN
#define MUI_MESSAGES_PLUGIN
#define MUI_CLOCK_PLUGIN
#define MUI_MAP_PLUGIN
#define MUI_SETTINGS_PLUGIN
#endif

#if defined(VIEW_240x135)
#define MUI_SCROLLMENU_PLUGIN
#define MUI_DASHBOARD_PLUGIN
#define MUI_NODES_PLUGIN
#define MUI_GROUPS_PLUGIN
#define MUI_MESSAGES_PLUGIN
#define MUI_CLOCK_PLUGIN
#define MUI_MAP_PLUGIN
#define MUI_SETTINGS_PLUGIN
#endif

#if defined(VIEW_160x80)
#define MUI_SCROLLMENU_PLUGIN
#define MUI_DASHBOARD_PLUGIN
#define MUI_NODES_PLUGIN
#define MUI_GROUPS_PLUGIN
#define MUI_MESSAGES_PLUGIN
#define MUI_CLOCK_PLUGIN
#define MUI_MAP_PLUGIN
#define MUI_SETTINGS_PLUGIN
#endif
