#include "DeviceGUI.h"
#include "lvgl.h"
#include "ui.h" // this is the lvgl ui generated by squareline editor; set build flag -I to its location in the platformio.ini variant
#include "Arduino.h"

DeviceGUI::DeviceGUI(DisplayDriver* driver) : displaydriver(driver) {
}

void DeviceGUI::init(void) {
    Serial.println("UI init...");
    ui_init();
}
