#include "DeviceGUI.h"
#include "lvgl.h"
#include "ui.h" // this is the lvgl ui generated by squareline editor; set build flag -I to its location in the platformio.ini variant
#include "Arduino.h"

DeviceGUI::DeviceGUI(DisplayDriver* driver, ViewController* _controller) : displaydriver(driver) {
    controller = _controller;
}

void DeviceGUI::init(IClientBase* client) {
    Serial.println("UI init...");
    ui_init();
    controller->init(client);
}

void DeviceGUI::task_handler(void) { 
    displaydriver->task_handler();
    controller->runOnce(); 
};
