#ifdef VIEW_128x64
#include "OLEDView_128x64.h"
#include <cstdio>
#include <ctime>
#include <functional>
#include "Arduino.h"
#include "ui.h" // this is the ui generated by lvgl / squareline editor

#ifdef USE_X11
#include "X11Driver.h"
#elif defined(PICO)
#include "OLEDDriver.h"
#else
#error "Unknown device for view 128x64"
#endif


OLEDView_128x64* OLEDView_128x64::gui = nullptr;

OLEDView_128x64* OLEDView_128x64::instance(void) {
    if (!gui) gui = new OLEDView_128x64;
    return gui;
}

#ifdef USE_X11
OLEDView_128x64::OLEDView_128x64() : DeviceGUI(&X11Driver::create()) {
}
#else
OLEDView_128x64::OLEDView_128x64() : DeviceGUI(new OLEDDriver<OLED_DRIVER>(screenWidth, screenHeight)) {
}
#endif

void OLEDView_128x64::init(void) {
    Serial.println("OLEDView init...");
    displaydriver->init();
    DeviceGUI::init();
    //ui_set_active(ui_HomeButton, ui_HomePanel, ui_TopPanel);
    //ui_events_init();

    // keyboard init
    //lv_keyboard_set_textarea(ui_Keyboard, ui_MessageInputArea);
}



void OLEDView_128x64::task_handler(void) {
    lv_timer_handler();
    displaydriver->task_handler();
}

#endif