#ifdef VIEW_128x64

#include "OLEDView_128x64.h"
#include <cstdio>
#include <ctime>
#include <functional>
#include "Arduino.h"
#include "ui.h" // this is the ui generated by lvgl / squareline editor

#ifdef USE_X11
#include "X11Driver.h"
#elif defined(OLED_DRIVER)
#include OLED_DRIVER_INC
#else
#error "Unknown device for view 128x64"
#endif


OLEDView_128x64* OLEDView_128x64::gui = nullptr;

OLEDView_128x64* OLEDView_128x64::instance(void) {
    if (!gui) gui = new OLEDView_128x64;
    return gui;
}

#ifdef USE_X11
OLEDView_128x64::OLEDView_128x64() : DeviceGUI(&X11Driver::create(), new ViewController) {
}
#else
OLEDView_128x64::OLEDView_128x64() : DeviceGUI(new OLEDDriver<OLED_DRIVER>(screenWidth, screenHeight),
                                               new OLEDViewController) {
}
#endif

void OLEDView_128x64::init(IClientBase* client) {
    Serial.println("OLEDView init...");
    displaydriver->init();
    DeviceGUI::init(client);
    //ui_events_init();
}

#endif