#ifdef VIEW_240x240
#include "TFTView_240x240.h"
#include <cstdio>
#include <ctime>
#include <functional>
#include "Arduino.h"
#include "ui.h" // this is the ui generated by lvgl / squareline editor

#ifdef USE_X11
#include "X11Driver.h"
#elif defined(T_WATCH_S3)
#include "LGFXDriver.h"
#include "LGFX_T_WATCH_S3.h"
#else
#error "Unknown device for view 240x240"
#endif


TFTView_240x240* TFTView_240x240::gui = nullptr;

TFTView_240x240* TFTView_240x240::instance(void) {
    if (!gui) gui = new TFTView_240x240;
    return gui;
}

#ifdef USE_X11
TFTView_240x240::TFTView_240x240() : DeviceGUI(&X11Driver::create()) {
}
#else
TFTView_240x240::TFTView_240x240() : DeviceGUI(new LGFXDriver<LGFX_DRIVER>(screenWidth, screenHeight)) {
}
#endif

void TFTView_240x240::init(void) {
    Serial.println("TFTView init...");
    displaydriver->init();
    DeviceGUI::init();
    //ui_set_active(ui_HomeButton, ui_HomePanel, ui_TopPanel);
    //ui_events_init();

    // keyboard init
    //lv_keyboard_set_textarea(ui_Keyboard, ui_MessageInputArea);
}



void TFTView_240x240::task_handler(void) {
    DeviceGUI::task_handler();
}

#endif