#ifdef VIEW_160x80

#include "TFTView_160x80.h"
#include <cstdio>
#include <ctime>
#include <functional>
#include "Arduino.h"
#include "ui.h" // this is the ui generated by lvgl / squareline editor

#ifdef USE_X11
#include "X11Driver.h"
#elif defined (HELTEC_TRACKER)
#include "LGFXDriver.h"
#include "LGFX_HELTEC_TRACKER.h"
#else
#error "Unknown device for view 160x80"
#endif

#ifdef USE_X11
TFTView_160x80::TFTView_320x240() : DeviceGUI(&X11Driver::create()) {
}
#else
TFTView_160x80::TFTView_320x240() : DeviceGUI(new LGFXDriver<LGFX_HELTEC_TRACKER>(screenWidth, screenHeight)) {
}
#endif


#endif