#ifdef VIEW_480x320

#include "TFTView_480x320.h"
#include <cstdio>
#include <ctime>
#include <functional>
#include "Arduino.h"
#include "ui.h" // this is the ui generated by lvgl / squareline editor

#ifdef USE_X11
#include "X11Driver.h"
#elif defined (WT32_SC01)
#include "LGFXDriver.h"
#include "LGFX_WT_SC01PLUS.h"
#else
#error "Unknown device for view 480x320"
#endif

#ifdef USE_X11
TFTView_480x320::TFTView_320x240() : DeviceGUI(&X11Driver::create()) {
}
#else
TFTView_480x320::TFTView_320x240() : DeviceGUI(new LGFXDriver<LGFX_WT_SC01PLUS>(screenWidth, screenHeight)) {
}
#endif


#endif