name: Nightly
on:
  schedule:
    - cron: 0 8 * * 1-5 # Nightly at 8am on weekdays
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk_upgrade:
    # See: https://github.com/trunk-io/trunk-action/blob/v1/readme.md#automatic-upgrades
    name: Trunk Upgrade (PR)
    runs-on: ubuntu-24.04
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          base: master
